import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import '../models/student.dart';
import '../constants.dart';

void showUniversalEmergencyCard(BuildContext context, Student student) {
  showDialog(
    context: context,
    builder: (ctx) => EmergencyCardDialog(student: student),
  );
}

class EmergencyCardDialog extends StatefulWidget {
  final Student student;
  const EmergencyCardDialog({super.key, required this.student});

  @override
  State<EmergencyCardDialog> createState() => _EmergencyCardDialogState();
}

class _EmergencyCardDialogState extends State<EmergencyCardDialog> {
  String? _secureLink;
  bool _isGenerating = true;

  @override
  void initState() {
    super.initState();
    _generateSecureLink();
  }

  Future<void> _generateSecureLink() async {
    String token = "${DateTime.now().millisecondsSinceEpoch}_${widget.student.id}";
    String origin = kIsWeb ? Uri.base.origin : "https://varsityvault-324f5.web.app";
    String link = "$origin/?card=$token";

    try {
      await FirebaseFirestore.instance.collection('public_cards').doc(token).set({
        'expiresAt': DateTime.now().add(const Duration(hours: 24)).millisecondsSinceEpoch,
        'studentData': widget.student.toJson()
      });
      
      if (mounted) {
        setState(() {
          _secureLink = link;
          _isGenerating = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _isGenerating = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: Colors.white, 
      contentPadding: EdgeInsets.zero,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      content: EmergencyCardLayout(
        student: widget.student,
        bottomSection: _isGenerating
          ? const Padding(
              padding: EdgeInsets.all(40.0),
              child: Center(child: Column(
                children: [
                  CircularProgressIndicator(color: kErrorRed),
                  SizedBox(height: 15),
                  Text("Generating secure 24-hr link...", style: TextStyle(color: Colors.grey))
                ],
              )),
            )
          : Column(
              children: [
                // FIX: Forced the Quiet Zone (padding) and strict High Contrast Colors!
                Container(
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border.all(color: Colors.black12, width: 2),
                    borderRadius: BorderRadius.circular(8)
                  ),
                  child: QrImageView(
                    data: _secureLink ?? "", 
                    version: QrVersions.auto, 
                    size: 160.0,
                    backgroundColor: Colors.white, 
                    foregroundColor: Colors.black,
                    padding: const EdgeInsets.all(12),
                  ),
                ),
                const SizedBox(height: 5),
                const Center(child: Text("Scan to view digital medical card", style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold))),
                const Center(child: Text("Link expires securely in 24 hours", style: TextStyle(color: kErrorRed, fontSize: 10, fontWeight: FontWeight.bold))),
              ],
            )
      ),
    );
  }
}

class PublicEmergencyCardScreen extends StatelessWidget {
  final String token;
  const PublicEmergencyCardScreen({super.key, required this.token});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        title: const Text("Varsity Vault: Secure Medical Access", style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: kErrorRed,
        foregroundColor: Colors.white,
        centerTitle: true,
      ),
      body: FutureBuilder<DocumentSnapshot>(
        future: FirebaseFirestore.instance.collection('public_cards').doc(token).get(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator(color: kErrorRed));
          }
          
          if (!snapshot.hasData || !snapshot.data!.exists) {
            return _errorScreen("Invalid or missing medical token.");
          }

          var data = snapshot.data!.data() as Map<String, dynamic>;
          int expiresAt = data['expiresAt'] ?? 0;

          if (DateTime.now().millisecondsSinceEpoch > expiresAt) {
            return _errorScreen("For security purposes, this medical link has expired. A new QR code must be generated by the coaching staff.");
          }

          Student s = Student.fromJson(data['studentData']);
          
          return Center(
            child: SingleChildScrollView(
              padding: const EdgeInsets.symmetric(vertical: 30, horizontal: 10),
              child: Card(
                elevation: 10,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                child: EmergencyCardLayout(
                  student: s,
                  bottomSection: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(15),
                    color: Colors.green.withOpacity(0.1),
                    child: const Column(
                      children: [
                        Icon(Icons.verified_user, color: Colors.green, size: 40),
                        SizedBox(height: 5),
                        Text("Connection Secure", style: TextStyle(color: Colors.green, fontWeight: FontWeight.bold)),
                        Text("Data fetched directly from school district servers.", style: TextStyle(color: Colors.black54, fontSize: 10)),
                      ],
                    )
                  )
                )
              )
            )
          );
        },
      )
    );
  }

  Widget _errorScreen(String msg) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(30.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.security, color: Colors.grey, size: 80),
            const SizedBox(height: 20),
            const Text("Access Denied", style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
            const SizedBox(height: 10),
            Text(msg, textAlign: TextAlign.center, style: const TextStyle(color: Colors.black54)),
          ],
        ),
      )
    );
  }
}

class EmergencyCardLayout extends StatelessWidget {
  final Student student;
  final Widget bottomSection;

  const EmergencyCardLayout({super.key, required this.student, required this.bottomSection});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 450, 
      child: SingleChildScrollView( 
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              decoration: const BoxDecoration(color: kErrorRed, borderRadius: BorderRadius.vertical(top: Radius.circular(12))),
              padding: const EdgeInsets.all(15), 
              width: double.infinity,
              child: const Text("MEDICAL EMERGENCY CARD", textAlign: TextAlign.center, style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 18, letterSpacing: 1.2)),
            ),
            Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
                    Expanded(child: Text(student.fullName, style: const TextStyle(fontSize: 26, fontWeight: FontWeight.bold, color: Colors.black))),
                    Text("Age: ${student.age}", style: const TextStyle(fontSize: 18, color: Colors.black54, fontWeight: FontWeight.bold)),
                  ]),
                  const SizedBox(height: 5),
                  Text("DOB: ${student.dob.month}/${student.dob.day}/${student.dob.year}  |  ID: ${student.id}  |  Grade: ${student.grade}", style: const TextStyle(color: Colors.black87, fontWeight: FontWeight.bold)),
                  Text("Sex: ${student.sex}  |  Height: ${student.height}  |  Weight: ${student.weight}", style: const TextStyle(color: Colors.black87)),
                  const SizedBox(height: 5),
                  Text("Address: ${student.fullAddress}", style: const TextStyle(color: Colors.black87)),
                  Text("Student Phone: ${student.mobilePhone.isEmpty ? student.homePhone : student.mobilePhone}", style: const TextStyle(color: Colors.black87)),
                  Text("Student Email: ${student.email}", style: const TextStyle(color: Colors.black87)),
                  
                  const Divider(color: Colors.black26, thickness: 1.5, height: 30),
                  
                  const Text("MEDICAL INFORMATION", style: TextStyle(fontWeight: FontWeight.bold, color: kErrorRed, fontSize: 14)),
                  const SizedBox(height: 8),
                  RichText(text: TextSpan(style: const TextStyle(color: Colors.black87, fontSize: 14), children: [
                    const TextSpan(text: "Allergies/Conditions: ", style: TextStyle(fontWeight: FontWeight.bold)),
                    TextSpan(
                      text: student.medicalConditions.isEmpty ? 'None' : student.medicalConditions,
                      style: TextStyle(color: student.medicalConditions.isNotEmpty ? Colors.red : Colors.black87, fontWeight: student.medicalConditions.isNotEmpty ? FontWeight.bold : FontWeight.normal)
                    ),
                  ])),
                  const SizedBox(height: 8),
                  Text("Physician: ${student.physicianName.isEmpty ? 'None Provided' : student.physicianName}", style: const TextStyle(color: Colors.black87, fontWeight: FontWeight.bold)),
                  Text("Phone: ${student.physicianPhone.isEmpty ? 'None Provided' : student.physicianPhone}", style: const TextStyle(color: Colors.black87)),
                  const SizedBox(height: 8),
                  Text("Hospital Pref: ${student.hospitalPreference} ${student.hospitalLocation.isNotEmpty ? '(${student.hospitalLocation})' : ''}", style: const TextStyle(color: Colors.black87)),
                  
                  if (student.isInsured) ...[
                    const SizedBox(height: 8),
                    Text("Insurance: ${student.insuranceCompany}", style: const TextStyle(color: Colors.black87)),
                    Text("Policy #: ${student.insurancePolicyNum}", style: const TextStyle(color: Colors.black87)),
                  ],

                  const Divider(color: Colors.black26, thickness: 1.5, height: 30),
                  
                  const Text("EMERGENCY CONTACTS", style: TextStyle(fontWeight: FontWeight.bold, color: kErrorRed, fontSize: 14)),
                  const SizedBox(height: 10),
                  _buildContactRow("Primary Emergency Contact", "${student.emgFirst} ${student.emgLast} (${student.emgRelation})", student.emgPhone, ""),
                  const SizedBox(height: 10),
                  _buildContactRow("Parent/Guardian 1", "${student.p1First} ${student.p1Last}", student.p1Mobile, student.p1Email),
                  
                  if (student.livingArrangement == "Both Parents" && student.p2First.isNotEmpty) ...[
                     const SizedBox(height: 10),
                     _buildContactRow("Parent/Guardian 2", "${student.p2First} ${student.p2Last}", student.p2Mobile, student.p2Email),
                  ],
                  
                  const SizedBox(height: 30),
                  
                  bottomSection
                ],
              ),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildContactRow(String title, String name, String phone, String email) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(title, style: const TextStyle(fontSize: 11, color: Colors.black54, fontWeight: FontWeight.bold)),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Expanded(child: Text(name, style: const TextStyle(color: Colors.black87, fontWeight: FontWeight.bold, fontSize: 15))),
            Text(phone, style: const TextStyle(color: Colors.black87, fontWeight: FontWeight.bold, fontSize: 15)),
          ]
        ),
        if (email.isNotEmpty) Text(email, style: const TextStyle(color: Colors.blue, fontSize: 12)),
      ]
    );
  }
}